name: license_xml_parser
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
